apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-prod
  namespace: cert-manager
spec:
  secretName: wildcard-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.${domain_name}"
  dnsNames:
    - "*.${domain_name}"
