defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
enabled: true
controller:
  manager:
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi